# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_valid_nt_fasta_format <- function(file_lines) {
    .Call('quickfastacheck_is_valid_nt_fasta_format', PACKAGE = 'quickfastacheck', file_lines)
}

rcpp_hello_world <- function() {
    .Call('quickfastacheck_rcpp_hello_world', PACKAGE = 'quickfastacheck')
}

